basePath: /
definitions:
  handler.forgotPasswordForm:
    properties:
      email:
        type: string
    type: object
  handler.loginForm:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.registerForm:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handler.scheduleForm:
    properties:
      contributor:
        type: string
      description:
        type: string
      end_date:
        type: integer
      name:
        type: string
      start_date:
        type: integer
      type:
        type: string
    type: object
  handler.taskForm:
    properties:
      contributor:
        type: string
      description:
        type: string
      end_date:
        type: integer
      name:
        type: string
      project_id:
        type: string
      start_date:
        type: integer
    type: object
info:
  contact: {}
  description: Proman Backend API
  title: Proman Backend
paths:
  /api/forgot-password:
    post:
      consumes:
      - application/json
      operationId: forgot-password
      parameters:
      - description: forgot password json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.forgotPasswordForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ForgotPassword
      tags:
      - Auth
  /api/login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: login json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.loginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Login
      tags:
      - Auth
  /api/me:
    get:
      consumes:
      - application/json
      operationId: me
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get my info
      tags:
      - Me
  /api/me/schedule:
    get:
      consumes:
      - application/json
      operationId: my-schedule
      parameters:
      - description: Search by name
        in: query
        name: q
        type: string
      - description: Search by type
        enum:
        - all
        - meeting
        - discussion
        - review
        - presentation
        - etc
        in: query
        name: type
        type: string
      - description: Start date
        in: query
        name: start
        type: string
      - description: End date
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get my schedule
      tags:
      - Me
  /api/project:
    get:
      consumes:
      - application/json
      operationId: list-project
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get list of project
      tags:
      - Project
    post:
      consumes:
      - application/json
      operationId: create-project
      parameters:
      - description: Project name
        in: formData
        name: name
        required: true
        type: string
      - description: Project description
        in: formData
        name: description
        required: true
        type: string
      - description: Project start date
        in: formData
        name: start_date
        required: true
        type: integer
      - description: Project end date
        in: formData
        name: end_date
        required: true
        type: integer
      - description: Project contributor
        in: formData
        name: contributor
        required: true
        type: string
      - description: Project type
        in: formData
        name: type
        required: true
        type: string
      - description: Project logo
        in: formData
        name: logo
        type: file
      - description: Project attachments
        in: formData
        name: attachments
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create project
      tags:
      - Project
  /api/project/{id}:
    delete:
      consumes:
      - application/json
      operationId: delete-project
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Delete project by id
      tags:
      - Project
    get:
      consumes:
      - application/json
      operationId: get-project
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get project by id
      tags:
      - Project
  /api/project/count:
    get:
      consumes:
      - application/json
      operationId: project-count
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get project count
      tags:
      - Project
  /api/project/count/type:
    get:
      consumes:
      - application/json
      operationId: project-count-type
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get project count by type
      tags:
      - Project
  /api/project/user/{id}:
    get:
      consumes:
      - application/json
      operationId: list-project-user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get list of project by user
      tags:
      - Project
  /api/register:
    post:
      consumes:
      - application/json
      operationId: register
      parameters:
      - description: register json
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.registerForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Register
      tags:
      - Auth
  /api/schedule:
    post:
      consumes:
      - application/json
      operationId: schedule-create
      parameters:
      - description: Schedule data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.scheduleForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create schedule
      tags:
      - Schedule
  /api/task:
    post:
      consumes:
      - application/json
      operationId: task-create
      parameters:
      - description: Task data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.taskForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create task
      tags:
      - Task
  /api/task/{id}:
    delete:
      consumes:
      - application/json
      operationId: task-delete
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Delete task
      tags:
      - Task
  /api/task/count:
    get:
      consumes:
      - application/json
      operationId: task-count
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get task count
      tags:
      - Task
  /api/user/count:
    get:
      consumes:
      - application/json
      operationId: user-count
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get user count
      tags:
      - User
  /api/user/latest:
    get:
      consumes:
      - application/json
      operationId: user-latest
      parameters:
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - default: '"desc"'
        description: Sort
        enum:
        - desc
        - asc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Get latest users joined
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
